---
title: "OSW New Word Probability Analysis"
author: "AndrewLampinen"
date: "October 23, 2017"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(xtable)
```


```{r}
words = c("borrow", "cowboys", "immune", "rice") 

num_train = c(1, 10)
perms = 1
Approaches = c("opt_centroid", "centroid")
presences = c("wordpresent", "wordabsent")

d = data.frame()
for (word in words) {
  for (perm in perms) {
    for (n in num_train) {
      for (a in Approaches) {
        for (presence in presences) {
          filename = sprintf("../error_analysis/%s/perm%i_numtrain%i_%s_%s_error_analysis.csv", word, perm, n, a, presence)
          if (!file.exists(filename)) {
            next
          }
          this_d = read.csv(filename, header=T)
          this_d = this_d %>% 
            mutate(new_word=word, perm=perm, num_train=n, Approach=a, presence=presence)
          d = bind_rows(d, this_d)
        }
        
      }
    }
  }
  # Pre 
  for (presence in presences) {
    filename = sprintf("../error_analysis/%s/pre_%s_error_analysis.csv", word, presence)
      if (!file.exists(filename)) {
        next
      }
      this_d2 = read.csv(filename, header=T)
      this_d2 = this_d2 %>% 
        mutate(new_word=word, perm=NA, num_train=10, Approach='pre', presence=presence)
      d = bind_rows(d, this_d2)
  }
  # With word
  for (presence in presences) {
    filename = sprintf("../error_analysis/%s/withword_%s_error_analysis.csv", word, presence)
      if (!file.exists(filename)) {
        next
      }
      this_d2 = read.csv(filename, header=T)
      this_d2 = this_d2 %>% 
        mutate(new_word=word, perm=NA, num_train=10, Approach='with_word', presence=presence)
      d = bind_rows(d, this_d2)
  }
  
}

```

```{r}
d = d %>%
  mutate(this_is_new_word=new.word.index==target,
         num_train=as.integer(num_train))
```

```{r}
summary_d = d %>%
  filter(Approach != 'pre') %>%
  group_by(presence, this_is_new_word, Approach, num_train) %>%
  summarize(mean.new.word.log.prob = mean(new.word.log.probability)) %>%
  ungroup() %>%
  mutate(test_type=ifelse(this_is_new_word, 'New word is correct', ifelse(presence=='wordpresent', 'Wrong but relevant', 'Wrong and irrelevant'))) %>%
  select(-presence, -this_is_new_word)
summary_d
```
```{r}
xtable(
summary_d %>%
  filter(num_train==10) %>%
  select(-num_train) %>%
  spread(test_type, mean.new.word.log.prob)
)
```

```{r}
xtable(
summary_d %>%
  spread(test_type, mean.new.word.log.prob)
)
```
```{r}

summary_by_word_d = d %>%
  filter(Approach != 'pre') %>%
  group_by(presence, this_is_new_word, new_word, num_train, Approach) %>%
  summarize(mean.new.word.log.prob = mean(new.word.log.probability)) %>%
  ungroup() %>%
  mutate(test_type=ifelse(this_is_new_word, 'New word is correct', ifelse(presence=='wordpresent', 'Wrong but relevant', 'Wrong and irrelevant'))) %>%
  select(-presence, -this_is_new_word)
summary_by_word_d
```

```{r}

print(xtable(
summary_by_word_d %>%
  spread(test_type, mean.new.word.log.prob)
), include.rownames = F)
```

